uploads = []

[[generated]]
id = "7iPiYsiJhxlU6pXadfhXs"
uri = "file://artifacts/dashboard-deck/public/hero-bg.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "H7rnKKAydZ4PUnNwlpCVZ"
uri = "file://.local/outputs/Content-Freshness-Dashboard.pdf"
type = "pdf"
title = "Content Freshness Dashboard.pdf"

[[outputs]]
id = "NrrywYBwtWrVSfoVWlOAu"
uri = "file://.local/outputs/Content-Freshness-Dashboard.pptx"
type = "slides"
title = "Content Freshness Dashboard.pptx"

[[outputs]]
id = "4YeWz_ylm99Mmj-umpdKv"
uri = "file://content-freshness-dashboard.tar.gz"
type = "unspecified"
title = "Content Freshness Dashboard - Project Archive"
